import React, { useState, useEffect, useMemo, useRef } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { 
  TrendingUp, Activity, Newspaper, ShieldAlert, 
  DollarSign, BarChart2, Search, Target, Zap, Info
} from 'lucide-react';
import PriceChart from './PriceChart.jsx';
import SymbolSearchDropdown from './SymbolSearchDropdown.jsx';
import { formatDisplayTicker, prepareCustomTicker } from './tickerDisplay.js';

const tooltips = {
  buffett: "Evaluates durable competitive advantage based on gross margin stability, and calculates intrinsic value using a DCF model.",
  garp: "Growth At a Reasonable Price. Looks for strong growth (low PEG ratio) to avoid overpaying.",
  magic_formula: "Ranks stocks by high earnings yield and high return on capital to find good companies at bargain prices.",
  factor: "Evaluates quantitative factors like Value (Price to Book) and Momentum (6-month performance).",
  trailing_pe: "Price-to-Earnings ratio based on the last 12 months.",
  forward_pe: "Price-to-Earnings ratio based on estimated next 12 months.",
  dividend_yield: "Annual dividend per share divided by the current share price.",
  price_to_book: "Ratio of market value to book value of equity.",
  return_on_equity: "Net income returned as a percentage of shareholders equity.",
  gross_margins: "Percentage of revenue left after deducting the cost of goods sold.",
  free_cash_flow: "Cash generated after accounting for cash outflows to support operations.",
  total_revenue: "Total amount of income generated by the sale of goods or services.",
  ebitda: "Earnings before interest, taxes, depreciation, and amortization.",
  default: "Financial metric utilized in the fundamental analysis."
};

const MARKET_TABS = [
  { id: 'us_stocks', label: 'US' },
  { id: 'india_stocks', label: 'India' },
  { id: 'global_indices', label: 'Indices' },
  { id: 'forex', label: 'Forex' },
  { id: 'crypto', label: 'Crypto' },
  { id: 'commodities', label: 'Commodities' },
];

const isEquityAsset = (assetClass) =>
  assetClass === 'us_equity' || assetClass === 'india_equity';

const fundamentalCategories = [
  { name: 'Valuation', keys: ['market_cap', 'enterprise_value', 'trailing_pe', 'forward_pe', 'price_to_book'] },
  { name: 'Profitability', keys: ['profit_margins', 'operating_margins', 'return_on_equity'] },
  { name: 'Growth', keys: ['revenue_growth', 'earnings_growth', 'earnings_quarterly_growth'] },
  { name: 'Financial Health', keys: ['debt_to_equity', 'current_ratio', 'quick_ratio', 'derived_current_ratio', 'total_debt_info', 'total_debt', 'total_cash_info', 'cash_and_equivalents', 'current_assets', 'current_liabilities', 'total_assets', 'stockholders_equity', 'book_value'] },
  { name: 'Income Statement', keys: ['total_revenue', 'net_income', 'operating_income'] },
  { name: 'Cash Flow & Dividends', keys: ['free_cashflow', 'operating_cashflow', 'dividend_yield', 'payout_ratio'] },
  { name: 'Market Dynamics', keys: ['beta'] }
];

const formatLargeNumber = (value) => {
  if (typeof value !== 'number') return value;
  if (Math.abs(value) >= 1.0e12) {
    return (value / 1.0e12).toFixed(2) + 'T';
  } else if (Math.abs(value) >= 1.0e9) {
    return (value / 1.0e9).toFixed(2) + 'B';
  } else if (Math.abs(value) >= 1.0e6) {
    return (value / 1.0e6).toFixed(2) + 'M';
  }
  return value.toLocaleString(undefined, { maximumFractionDigits: 2 });
};

function App() {
  const [universe, setUniverse] = useState([]);
  const [selectedStock, setSelectedStock] = useState(null);
  const [analysis, setAnalysis] = useState(null);
  const [loadingUniverse, setLoadingUniverse] = useState(false);
  const [loadingAnalysis, setLoadingAnalysis] = useState(false);
  const [error, setError] = useState('');
  const [searchQuery, setSearchQuery] = useState('');
  const [selectedMarket, setSelectedMarket] = useState('us_stocks');
  const [remoteSuggestions, setRemoteSuggestions] = useState([]);
  const [searchLoading, setSearchLoading] = useState(false);
  const [showDropdown, setShowDropdown] = useState(false);
  const [highlightIndex, setHighlightIndex] = useState(0);
  const searchInputRef = useRef(null);

  useEffect(() => {
    const fetchUniverse = async () => {
      setLoadingUniverse(true);
      setError('');
      try {
        const response = await fetch(`/api/stocks/universe?market=${selectedMarket}`);
        if (!response.ok) {
          const errorData = await response.json().catch(() => ({}));
          throw new Error(errorData.detail || 'Failed to fetch market universe.');
        }
        const data = await response.json();
        setUniverse(data.stocks || []);
      } catch (err) {
        setError(err.message);
      } finally {
        setLoadingUniverse(false);
      }
    };
    fetchUniverse();
  }, [selectedMarket]);

  const handleAnalyze = async (ticker) => {
    const normalized = ticker.trim().toUpperCase();
    if (!normalized) return;

    setSelectedStock(normalized);
    setLoadingAnalysis(true);
    setAnalysis(null);
    setError('');
    try {
      const response = await fetch(`/api/stocks/analyze/${encodeURIComponent(normalized)}`);
      if (!response.ok) {
        const errorData = await response.json();
        throw new Error(errorData.detail || 'Failed to fetch analysis.');
      }
      const data = await response.json();
      setAnalysis(data);
    } catch (err) {
      setError(err.message);
    } finally {
      setLoadingAnalysis(false);
    }
  };

  const trimmedSearch = searchQuery.trim();
  const preparedCustomTicker = trimmedSearch
    ? prepareCustomTicker(trimmedSearch, selectedMarket)
    : '';

  const isInUniverse = (ticker) =>
    universe.some((s) => s.ticker.toUpperCase() === ticker.toUpperCase());

  const hasExactUniverseMatch =
    !!trimmedSearch &&
    universe.some(
      (s) =>
        s.ticker.toLowerCase() === trimmedSearch.toLowerCase() ||
        s.ticker.toLowerCase() === preparedCustomTicker.toLowerCase() ||
        (s.display_ticker || '').toLowerCase() === trimmedSearch.toLowerCase()
    );

  const showCustomSearch = !!trimmedSearch && !hasExactUniverseMatch;
  const isCustomSelection = !!selectedStock && !isInUniverse(selectedStock);

  const runCustomSearch = () => {
    if (!preparedCustomTicker) return;
    handleAnalyze(preparedCustomTicker);
  };

  const selectSuggestion = (item) => {
    setSearchQuery(item.display_ticker || item.ticker);
    setShowDropdown(false);
    handleAnalyze(item.ticker);
  };

  const filteredUniverse = universe.filter((s) => {
    if (!trimmedSearch) return true;
    const q = trimmedSearch.toLowerCase();
    return (
      s.ticker.toLowerCase().includes(q) ||
      (s.display_ticker || '').toLowerCase().includes(q) ||
      s.name.toLowerCase().includes(q)
    );
  });

  const dropdownSuggestions = useMemo(() => {
    if (!trimmedSearch) return [];

    const local = filteredUniverse.slice(0, 5).map((s) => ({
      ticker: s.ticker,
      display_ticker: s.display_ticker || formatDisplayTicker(s.ticker),
      name: s.name,
      exchange: s.exchange,
      in_universe: true,
      source: 'local',
    }));

    const localTickers = new Set(local.map((s) => s.ticker.toUpperCase()));
    const remote = remoteSuggestions
      .filter((r) => !localTickers.has(r.ticker.toUpperCase()))
      .map((r) => ({ ...r, source: 'remote' }));

    return [...local, ...remote].slice(0, 10);
  }, [trimmedSearch, filteredUniverse, remoteSuggestions]);

  useEffect(() => {
    setHighlightIndex(0);
  }, [trimmedSearch, dropdownSuggestions.length]);

  useEffect(() => {
    if (trimmedSearch.length < 2) {
      setRemoteSuggestions([]);
      setSearchLoading(false);
      return undefined;
    }

    const controller = new AbortController();
    setSearchLoading(true);

    const timer = setTimeout(async () => {
      try {
        const response = await fetch(
          `/api/stocks/search?q=${encodeURIComponent(trimmedSearch)}&market=${selectedMarket}&limit=8`,
          { signal: controller.signal }
        );
        if (!response.ok) {
          setRemoteSuggestions([]);
          return;
        }
        const data = await response.json();
        setRemoteSuggestions(data.results || []);
      } catch (err) {
        if (err.name !== 'AbortError') {
          setRemoteSuggestions([]);
        }
      } finally {
        setSearchLoading(false);
      }
    }, 300);

    return () => {
      clearTimeout(timer);
      controller.abort();
    };
  }, [trimmedSearch, selectedMarket]);

  const searchPlaceholderByMarket = {
    us_stocks: 'Search by name or symbol (e.g. Apple, Palantir)',
    india_stocks: 'Search by name or symbol (e.g. Reliance, TCS)',
    global_indices: 'Search by name or symbol (e.g. Nifty, S&P)',
    forex: 'Search pair (e.g. USD INR, EUR USD)',
    crypto: 'Search by name or symbol (e.g. Bitcoin, Solana)',
    commodities: 'Search by name or symbol (e.g. Gold, Oil)',
  };

  const containerVariants = {
    hidden: { opacity: 0 },
    visible: { opacity: 1, transition: { staggerChildren: 0.1 } }
  };

  const itemVariants = {
    hidden: { y: 20, opacity: 0 },
    visible: { y: 0, opacity: 1 }
  };

  return (
    <div className="min-h-screen p-4 md:p-8 flex flex-col items-center relative overflow-hidden">
      {/* Background Blobs for Animation */}
      <div className="absolute top-[-10%] left-[-10%] w-[40%] h-[40%] bg-accent-purple/20 rounded-full mix-blend-screen filter blur-[100px] animate-blob"></div>
      <div className="absolute top-[20%] right-[-10%] w-[40%] h-[40%] bg-accent-cyan/20 rounded-full mix-blend-screen filter blur-[100px] animate-blob animation-delay-2000"></div>
      
      <div className="w-full max-w-[1400px] relative z-10 flex flex-col h-[calc(100vh-4rem)]">
        <header className="mb-8 text-center md:text-left flex items-center gap-3">
          <div className="p-3 bg-gradient-to-br from-accent-purple to-accent-cyan rounded-xl shadow-lg">
            <Zap className="text-white w-6 h-6" />
          </div>
          <div>
            <h1 className="text-3xl font-bold bg-clip-text text-transparent bg-gradient-to-r from-white to-neutral-400">
              Nexus<span className="text-accent-cyan">AI</span>
            </h1>
            <p className="text-sm text-neutral-400 font-medium">Multi-Market Research</p>
          </div>
        </header>
        
        <div className="flex flex-col md:flex-row gap-6 flex-1 min-h-0">
          
          {/* Sidebar: Stock Universe */}
          <motion.div 
            initial={{ opacity: 0, x: -20 }}
            animate={{ opacity: 1, x: 0 }}
            className="w-full md:w-80 glass-panel flex flex-col overflow-hidden shrink-0"
          >
            <div className="p-5 border-b border-glass-border">
              <h2 className="text-lg font-semibold flex items-center gap-2 mb-3 text-white">
                <Target className="w-5 h-5 text-accent-cyan" /> Market Universe
              </h2>
              <div className="flex flex-wrap gap-1.5 mb-4">
                {MARKET_TABS.map((tab) => (
                  <button
                    key={tab.id}
                    type="button"
                    onClick={() => {
                      setSelectedMarket(tab.id);
                      setSearchQuery('');
                      setRemoteSuggestions([]);
                      setShowDropdown(false);
                    }}
                    className={`px-2.5 py-1 text-xs font-semibold rounded-lg transition-all ${
                      selectedMarket === tab.id
                        ? 'bg-accent-cyan/20 text-accent-cyan border border-accent-cyan/40'
                        : 'bg-neutral-800/50 text-neutral-400 border border-neutral-700 hover:border-neutral-500'
                    }`}
                  >
                    {tab.label}
                  </button>
                ))}
              </div>
              <div className="flex gap-2">
                <div className="relative flex-1">
                  <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-neutral-400" />
                  <input
                    ref={searchInputRef}
                    type="text"
                    placeholder={searchPlaceholderByMarket[selectedMarket]}
                    className="w-full bg-neutral-800/50 border border-neutral-700 rounded-lg pl-10 pr-4 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-accent-cyan focus:border-transparent transition-all"
                    value={searchQuery}
                    onChange={(e) => {
                      setSearchQuery(e.target.value);
                      setShowDropdown(true);
                    }}
                    onFocus={() => setShowDropdown(true)}
                    onBlur={() => {
                      window.setTimeout(() => setShowDropdown(false), 150);
                    }}
                    onKeyDown={(e) => {
                      if (e.key === 'ArrowDown' && dropdownSuggestions.length > 0) {
                        e.preventDefault();
                        setShowDropdown(true);
                        setHighlightIndex((index) =>
                          Math.min(index + 1, dropdownSuggestions.length - 1)
                        );
                        return;
                      }
                      if (e.key === 'ArrowUp' && dropdownSuggestions.length > 0) {
                        e.preventDefault();
                        setShowDropdown(true);
                        setHighlightIndex((index) => Math.max(index - 1, 0));
                        return;
                      }
                      if (e.key === 'Escape') {
                        setShowDropdown(false);
                        return;
                      }
                      if (e.key === 'Enter') {
                        e.preventDefault();
                        if (showDropdown && dropdownSuggestions[highlightIndex]) {
                          selectSuggestion(dropdownSuggestions[highlightIndex]);
                          return;
                        }
                        if (showCustomSearch) {
                          runCustomSearch();
                        } else if (filteredUniverse.length === 1) {
                          handleAnalyze(filteredUniverse[0].ticker);
                        } else if (hasExactUniverseMatch) {
                          const match = universe.find(
                            (s) =>
                              s.ticker.toLowerCase() === trimmedSearch.toLowerCase() ||
                              (s.display_ticker || '').toLowerCase() === trimmedSearch.toLowerCase()
                          );
                          if (match) handleAnalyze(match.ticker);
                        }
                      }
                    }}
                  />
                  {showDropdown && trimmedSearch && (searchLoading || dropdownSuggestions.length > 0) && (
                    <SymbolSearchDropdown
                      suggestions={dropdownSuggestions}
                      loading={searchLoading}
                      highlightIndex={highlightIndex}
                      onSelect={selectSuggestion}
                      onHighlight={setHighlightIndex}
                    />
                  )}
                </div>
                <button
                  type="button"
                  onClick={runCustomSearch}
                  disabled={!showCustomSearch || loadingAnalysis}
                  className="shrink-0 px-3 py-2 text-xs font-semibold rounded-lg bg-accent-cyan/20 text-accent-cyan border border-accent-cyan/40 hover:bg-accent-cyan/30 disabled:opacity-40 disabled:cursor-not-allowed transition-all"
                  title="Analyze symbol not in curated list"
                >
                  Analyze
                </button>
              </div>
              <p className="text-[10px] text-neutral-500 mt-2 leading-relaxed">
                Pick a suggestion from the dropdown — company names work too.
              </p>
            </div>
            
            <div className="flex-1 overflow-y-auto p-3 space-y-2">
              {loadingUniverse && (
                <div className="flex justify-center items-center h-20">
                  <div className="w-6 h-6 border-2 border-accent-cyan border-t-transparent rounded-full animate-spin"></div>
                </div>
              )}
              {error && !loadingUniverse && <p className="text-red-400 text-sm p-2 text-center bg-red-400/10 rounded">{error}</p>}
              
              <AnimatePresence>
                {isCustomSelection && (
                  <motion.div
                    key="active-custom"
                    layout
                    initial={{ opacity: 0, scale: 0.95 }}
                    animate={{ opacity: 1, scale: 1 }}
                    exit={{ opacity: 0, scale: 0.95 }}
                    className="w-full p-3 rounded-xl border bg-gradient-to-r from-accent-cyan/20 to-transparent border-accent-cyan/50 shadow-[inset_4px_0_0_0_#22d3ee]"
                  >
                    <div className="flex justify-between items-center">
                      <span className="font-bold text-white text-lg tracking-tight">
                        {formatDisplayTicker(selectedStock)}
                      </span>
                      <Activity className="w-4 h-4 text-accent-cyan animate-pulse" />
                    </div>
                    <span className="text-xs text-accent-cyan block mt-0.5">Custom symbol · full analysis</span>
                  </motion.div>
                )}
                {showCustomSearch && dropdownSuggestions.length === 0 && !searchLoading && (
                  <motion.button
                    key="custom-ticker"
                    layout
                    initial={{ opacity: 0, scale: 0.95 }}
                    animate={{ opacity: 1, scale: 1 }}
                    exit={{ opacity: 0, scale: 0.95 }}
                    whileHover={{ scale: 1.02 }}
                    whileTap={{ scale: 0.98 }}
                    onClick={runCustomSearch}
                    disabled={loadingAnalysis}
                    className="w-full text-left p-3 rounded-xl transition-all border bg-neutral-800/30 border-dashed border-accent-cyan/50 hover:bg-neutral-800/50 hover:border-accent-cyan disabled:opacity-60"
                  >
                    <div className="flex justify-between items-center">
                      <span className="font-bold text-accent-cyan text-lg tracking-tight">
                        {formatDisplayTicker(preparedCustomTicker)}
                      </span>
                      <Search className="w-4 h-4 text-accent-cyan" />
                    </div>
                    <span className="text-xs text-neutral-400 block mt-0.5">
                      Not in this universe — analyze on Yahoo Finance
                      {preparedCustomTicker !== trimmedSearch.toUpperCase() && (
                        <span className="text-neutral-500"> · resolves to {preparedCustomTicker}</span>
                      )}
                    </span>
                  </motion.button>
                )}
                {trimmedSearch && filteredUniverse.length === 0 && !showCustomSearch && (
                  <p className="text-xs text-neutral-500 text-center py-4 px-2">
                    No curated matches for &ldquo;{trimmedSearch}&rdquo;.
                  </p>
                )}
                {filteredUniverse.map((stock) => (
                  <motion.button
                    key={stock.ticker}
                    layout
                    initial={{ opacity: 0, scale: 0.95 }}
                    animate={{ opacity: 1, scale: 1 }}
                    exit={{ opacity: 0, scale: 0.95 }}
                    whileHover={{ scale: 1.02 }}
                    whileTap={{ scale: 0.98 }}
                    onClick={() => handleAnalyze(stock.ticker)}
                    className={`w-full text-left p-3 rounded-xl transition-all border ${
                      selectedStock === stock.ticker 
                        ? 'bg-gradient-to-r from-accent-cyan/20 to-transparent border-accent-cyan/50 shadow-[inset_4px_0_0_0_#22d3ee]' 
                        : 'bg-neutral-800/30 border-transparent hover:bg-neutral-800/50 hover:border-neutral-700'
                    }`}
                  >
                    <div className="flex justify-between items-center">
                      <span className="font-bold text-white text-lg tracking-tight">
                        {stock.display_ticker || formatDisplayTicker(stock.ticker)}
                      </span>
                      {selectedStock === stock.ticker && <Activity className="w-4 h-4 text-accent-cyan animate-pulse" />}
                    </div>
                    {stock.name &&
                      stock.name.toUpperCase() !==
                        (stock.display_ticker || formatDisplayTicker(stock.ticker)).toUpperCase() && (
                      <span className="text-xs text-neutral-400 truncate block mt-0.5">{stock.name}</span>
                    )}
                    {(stock.currency || stock.exchange) && (
                      <span className="text-[10px] text-neutral-500 mt-1 block">
                        {[stock.exchange, stock.currency].filter(Boolean).join(' · ')}
                      </span>
                    )}
                  </motion.button>
                ))}
              </AnimatePresence>
            </div>
          </motion.div>
          
          {/* Main Content: Analysis */}
          <motion.div 
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            className="flex-1 glass-panel overflow-hidden flex flex-col"
          >
            {loadingAnalysis ? (
              <div className="flex-1 overflow-y-auto p-6 md:p-8">
                <div className="mb-6">
                  <h2 className="text-3xl font-black text-white tracking-tight">
                    {formatDisplayTicker(selectedStock)}
                  </h2>
                  <p className="text-neutral-400 text-sm mt-1">Loading analysis...</p>
                </div>
                <PriceChart loading />
                <div className="flex flex-col items-center justify-center py-12">
                  <div className="w-10 h-10 border-4 border-accent-purple border-t-transparent rounded-full animate-spin mb-3"></div>
                  <p className="text-neutral-400 font-medium animate-pulse">Running quantitative models...</p>
                </div>
              </div>
            ) : error && !loadingAnalysis ? (
              <div className="flex-1 flex items-center justify-center p-8">
                <div className="glass-panel border-red-500/30 bg-red-500/10 p-6 text-center max-w-md">
                  <ShieldAlert className="w-12 h-12 text-red-400 mx-auto mb-4" />
                  <h3 className="text-lg font-bold text-white mb-2">Analysis Failed</h3>
                  <p className="text-red-200 text-sm">{error}</p>
                </div>
              </div>
            ) : !analysis ? (
              <div className="flex-1 flex flex-col items-center justify-center p-8 text-center opacity-60">
                <BarChart2 className="w-20 h-20 text-neutral-600 mb-6" />
                <h3 className="text-2xl font-bold text-neutral-300 mb-2">Awaiting Selection</h3>
                <p className="text-neutral-400 max-w-sm">Select a ticker from the market universe to generate a comprehensive AI-driven analysis.</p>
              </div>
            ) : (
              <div className="flex-1 overflow-y-auto p-6 md:p-8">
                <motion.div 
                  variants={containerVariants} 
                  initial="hidden" 
                  animate="visible"
                  className="space-y-8"
                >
                  {/* Header Card */}
                  <motion.div variants={itemVariants} className="flex flex-col md:flex-row justify-between items-start md:items-end pb-6 border-b border-neutral-700/50">
                    <div>
                      <div className="mb-2">
                        <h2 className="text-4xl font-black text-white tracking-tight flex items-center gap-3 flex-wrap">
                          {analysis.display_ticker || formatDisplayTicker(analysis.ticker)}
                          {isCustomSelection && (
                            <span className="text-xs px-2.5 py-1 rounded-full font-semibold bg-accent-cyan/15 text-accent-cyan border border-accent-cyan/30">
                              Custom
                            </span>
                          )}
                          <span className={`text-sm px-3 py-1 rounded-full font-bold uppercase tracking-wider ${
                            analysis.decision_brief.verdict === 'buy' || analysis.decision_brief.verdict === 'strong_buy' ? 'bg-green-500/20 text-green-400 border border-green-500/30' :
                            analysis.decision_brief.verdict === 'sell' || analysis.decision_brief.verdict === 'strong_sell' ? 'bg-red-500/20 text-red-400 border border-red-500/30' :
                            'bg-yellow-500/20 text-yellow-400 border border-yellow-500/30'
                          }`}>
                            {analysis.decision_brief.verdict.replace('_', ' ')}
                          </span>
                        </h2>
                        {analysis.name &&
                          analysis.name.toUpperCase() !==
                            (analysis.display_ticker || formatDisplayTicker(analysis.ticker)).toUpperCase() && (
                          <p className="text-neutral-300 text-lg mt-1">{analysis.name}</p>
                        )}
                      </div>
                      <div className="flex items-center gap-6 text-sm">
                        <div className="flex items-center gap-2">
                          <DollarSign className="w-4 h-4 text-neutral-400" />
                          <span className="text-2xl font-semibold text-white">{analysis.current_price.toFixed(2)}</span>
                        </div>
                        <div className="flex items-center gap-2">
                          <Activity className="w-4 h-4 text-neutral-400" />
                          <span className="text-neutral-300">RSI: {analysis.rsi.toFixed(2)}</span>
                        </div>
                      </div>
                    </div>
                  </motion.div>

                  <motion.div variants={itemVariants}>
                    <PriceChart data={analysis.price_history} />
                  </motion.div>

                  {/* Summary Bullets */}
                  <motion.div variants={itemVariants} className="bg-neutral-800/40 rounded-xl p-6 border border-neutral-700/50">
                    <h3 className="text-lg font-bold text-white mb-4 flex items-center gap-2">
                      <TrendingUp className="w-5 h-5 text-accent-cyan" /> Key Insights
                    </h3>
                    <ul className="space-y-3">
                      {analysis.decision_brief.summary_bullets.map((bullet, index) => (
                        <li key={index} className="flex items-start gap-3 text-neutral-300">
                          <div className="mt-1.5 w-1.5 h-1.5 rounded-full bg-accent-cyan shrink-0"></div>
                          <span className="leading-relaxed">{bullet}</span>
                        </li>
                      ))}
                    </ul>
                  </motion.div>

                  {!isEquityAsset(analysis.asset_class) && (
                    <motion.div variants={itemVariants} className="bg-yellow-500/10 border border-yellow-500/30 rounded-xl p-4 text-sm text-yellow-200">
                      Equity-only analysis (fundamentals and strategy frameworks) is not applicable for this asset class.
                    </motion.div>
                  )}

                  {/* Strategy Ratings Grid */}
                  {isEquityAsset(analysis.asset_class) && (
                  <motion.div variants={itemVariants}>
                    <h3 className="text-lg font-bold text-white mb-4 flex items-center gap-2">
                      <BarChart2 className="w-5 h-5 text-accent-purple" /> Strategy Alpha
                    </h3>
                    <div className="grid grid-cols-2 md:grid-cols-5 gap-4">
                      {Object.entries(analysis.strategy_ratings).map(([strategy, rating]) => (
                        <div key={strategy} className="bg-neutral-800/40 border border-neutral-700/50 rounded-xl p-4 flex flex-col items-center justify-center text-center group hover:bg-neutral-800/60 transition-colors">
                          <p className="text-xs uppercase tracking-wider text-neutral-400 mb-2 font-semibold">{strategy}</p>
                          <div className="relative mb-1">
                            <svg className="w-16 h-16 transform -rotate-90">
                              <circle cx="32" cy="32" r="28" stroke="currentColor" strokeWidth="4" fill="transparent" className="text-neutral-700" />
                              <circle cx="32" cy="32" r="28" stroke="currentColor" strokeWidth="4" fill="transparent" 
                                strokeDasharray={`${rating.score_1_10 * 17.6} 176`} 
                                className={`transition-all duration-1000 ${rating.score_1_10 > 7 ? 'text-green-400' : rating.score_1_10 > 4 ? 'text-yellow-400' : 'text-red-400'}`} 
                              />
                            </svg>
                            <span className="absolute inset-0 flex items-center justify-center text-xl font-bold text-white">{rating.score_1_10}</span>
                          </div>
                          <p className={`text-[10px] uppercase tracking-wide px-2 py-0.5 rounded-full mt-2 ${
                            rating.confidence === 'high' ? 'bg-green-500/10 text-green-400' : 
                            rating.confidence === 'low' ? 'bg-red-500/10 text-red-400' : 
                            'bg-yellow-500/10 text-yellow-400'
                          }`}>
                            {rating.confidence} Conf
                          </p>
                        </div>
                      ))}
                    </div>
                  </motion.div>
                  )}

                  {/* Strategy Frameworks */}
                  {isEquityAsset(analysis.asset_class) && analysis.strategy_frameworks && !analysis.strategy_frameworks.not_applicable && (
                    <motion.div variants={itemVariants} className="bg-neutral-800/40 rounded-xl p-6 border border-neutral-700/50">
                      <h3 className="text-lg font-bold text-white mb-4 flex items-center gap-2">
                        <Zap className="w-5 h-5 text-accent-purple" /> Strategy Frameworks
                      </h3>
                      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
                        {analysis.strategy_frameworks.buffett_quality_dcf && (
                          <div className="p-4 bg-neutral-800/60 rounded-lg border border-neutral-700 relative group">
                            <div className="flex justify-between items-start mb-3">
                              <h4 className="font-semibold text-sm text-accent-cyan">Buffett Quality</h4>
                              <div className="cursor-help relative shrink-0">
                                <Info className="w-3 h-3 text-neutral-500 hover:text-accent-cyan transition-colors" />
                                <div className="hidden group-hover:block absolute bottom-full right-0 mb-2 w-56 p-2 bg-neutral-900 border border-neutral-700 rounded shadow-xl text-xs text-neutral-300 z-50 whitespace-normal">
                                  {tooltips.buffett}
                                </div>
                              </div>
                            </div>
                            <p className="text-xs text-neutral-300 mb-1">Moat Pass: <span className="font-bold text-white">{analysis.strategy_frameworks.buffett_quality_dcf.moat_check?.pass ? 'Yes' : 'No'}</span></p>
                            <p className="text-xs text-neutral-300">Target Buy: <span className="font-bold text-white">${analysis.strategy_frameworks.buffett_quality_dcf.valuation_dcf?.target_buy_price?.toFixed(2) || 'N/A'}</span></p>
                          </div>
                        )}
                        {analysis.strategy_frameworks.garp && (
                          <div className="p-4 bg-neutral-800/60 rounded-lg border border-neutral-700 relative group">
                            <div className="flex justify-between items-start mb-3">
                              <h4 className="font-semibold text-sm text-accent-cyan">GARP</h4>
                              <div className="cursor-help relative shrink-0">
                                <Info className="w-3 h-3 text-neutral-500 hover:text-accent-cyan transition-colors" />
                                <div className="hidden group-hover:block absolute bottom-full right-0 mb-2 w-56 p-2 bg-neutral-900 border border-neutral-700 rounded shadow-xl text-xs text-neutral-300 z-50 whitespace-normal">
                                  {tooltips.garp}
                                </div>
                              </div>
                            </div>
                            <p className="text-xs text-neutral-300 mb-1">PEG Ratio: <span className="font-bold text-white">{analysis.strategy_frameworks.garp.peg_ratio?.toFixed(2) || 'N/A'}</span></p>
                            <p className="text-xs text-neutral-300">Signal: <span className="font-bold text-white uppercase">{analysis.strategy_frameworks.garp.signal || 'N/A'}</span></p>
                          </div>
                        )}
                        {analysis.strategy_frameworks.magic_formula && (
                          <div className="p-4 bg-neutral-800/60 rounded-lg border border-neutral-700 relative group">
                            <div className="flex justify-between items-start mb-3">
                              <h4 className="font-semibold text-sm text-accent-cyan">Magic Formula</h4>
                              <div className="cursor-help relative shrink-0">
                                <Info className="w-3 h-3 text-neutral-500 hover:text-accent-cyan transition-colors" />
                                <div className="hidden group-hover:block absolute bottom-full right-0 mb-2 w-56 p-2 bg-neutral-900 border border-neutral-700 rounded shadow-xl text-xs text-neutral-300 z-50 whitespace-normal">
                                  {tooltips.magic_formula}
                                </div>
                              </div>
                            </div>
                            <p className="text-xs text-neutral-300 mb-1">Earnings Yield: <span className="font-bold text-white">{analysis.strategy_frameworks.magic_formula.earnings_yield_pct?.toFixed(2) || 'N/A'}%</span></p>
                            <p className="text-xs text-neutral-300">ROIC: <span className="font-bold text-white">{analysis.strategy_frameworks.magic_formula.return_on_capital_pct?.toFixed(2) || 'N/A'}%</span></p>
                          </div>
                        )}
                        {analysis.strategy_frameworks.factor_metrics && (
                          <div className="p-4 bg-neutral-800/60 rounded-lg border border-neutral-700 relative group">
                            <div className="flex justify-between items-start mb-3">
                              <h4 className="font-semibold text-sm text-accent-cyan">Factor Metrics</h4>
                              <div className="cursor-help relative shrink-0">
                                <Info className="w-3 h-3 text-neutral-500 hover:text-accent-cyan transition-colors" />
                                <div className="hidden group-hover:block absolute bottom-full right-0 mb-2 w-56 p-2 bg-neutral-900 border border-neutral-700 rounded shadow-xl text-xs text-neutral-300 z-50 whitespace-normal">
                                  {tooltips.factor}
                                </div>
                              </div>
                            </div>
                            <p className="text-xs text-neutral-300 mb-1">Price/Book: <span className="font-bold text-white">{analysis.strategy_frameworks.factor_metrics.price_to_book?.toFixed(2) || 'N/A'}</span></p>
                            <p className="text-xs text-neutral-300">6m Momentum: <span className="font-bold text-white">{analysis.strategy_frameworks.factor_metrics.momentum_6m_pct?.toFixed(2) || 'N/A'}%</span></p>
                          </div>
                        )}
                      </div>
                    </motion.div>
                  )}

                  {/* Fundamentals */}
                  {isEquityAsset(analysis.asset_class) && analysis.fundamentals && analysis.fundamentals.fields && Object.keys(analysis.fundamentals.fields).length > 0 && (
                    <motion.div variants={itemVariants} className="bg-neutral-800/40 rounded-xl p-6 border border-neutral-700/50">
                      <h3 className="text-lg font-bold text-white mb-6 flex items-center gap-2">
                        <Activity className="w-5 h-5 text-accent-cyan" /> Fundamentals ({analysis.fundamentals.currency})
                      </h3>
                      <div className="space-y-6">
                        {fundamentalCategories.map(category => {
                          const categoryFields = category.keys.filter(key => analysis.fundamentals.fields[key] !== undefined && analysis.fundamentals.fields[key] !== null);
                          if (categoryFields.length === 0) return null;
                          return (
                            <div key={category.name}>
                              <h4 className="text-sm font-semibold text-accent-cyan mb-3 border-b border-neutral-700/50 pb-1">{category.name}</h4>
                              <div className="grid grid-cols-2 md:grid-cols-4 lg:grid-cols-6 gap-3">
                                {categoryFields.map(key => {
                                  const value = analysis.fundamentals.fields[key];
                                  return (
                                    <div key={key} className="bg-neutral-800/50 p-2.5 rounded border border-neutral-700/50 relative group">
                                      <div className="flex justify-between items-start mb-1">
                                        <p className="text-[9px] text-neutral-400 uppercase tracking-wider pr-2 truncate" title={key.replace(/_/g, ' ')}>{key.replace(/_/g, ' ')}</p>
                                        <div className="cursor-help relative shrink-0">
                                          <Info className="w-2.5 h-2.5 text-neutral-500 hover:text-accent-cyan transition-colors" />
                                          <div className="hidden group-hover:block absolute bottom-full right-0 mb-2 w-48 p-2 bg-neutral-900 border border-neutral-700 rounded shadow-xl text-xs text-neutral-300 z-50 whitespace-normal">
                                            {tooltips[key] || tooltips.default}
                                          </div>
                                        </div>
                                      </div>
                                      <p className="text-xs font-bold text-white truncate" title={value}>{formatLargeNumber(value)}</p>
                                    </div>
                                  );
                                })}
                              </div>
                            </div>
                          );
                        })}
                        {(() => {
                          const allCategorizedKeys = new Set(fundamentalCategories.flatMap(c => c.keys));
                          const otherKeys = Object.keys(analysis.fundamentals.fields).filter(key => !allCategorizedKeys.has(key) && analysis.fundamentals.fields[key] !== null);
                          if (otherKeys.length === 0) return null;
                          return (
                            <div key="Other">
                              <h4 className="text-sm font-semibold text-accent-cyan mb-3 border-b border-neutral-700/50 pb-1">Other Metrics</h4>
                              <div className="grid grid-cols-2 md:grid-cols-4 lg:grid-cols-6 gap-3">
                                {otherKeys.map(key => {
                                  const value = analysis.fundamentals.fields[key];
                                  return (
                                    <div key={key} className="bg-neutral-800/50 p-2.5 rounded border border-neutral-700/50 relative group">
                                      <div className="flex justify-between items-start mb-1">
                                        <p className="text-[9px] text-neutral-400 uppercase tracking-wider pr-2 truncate" title={key.replace(/_/g, ' ')}>{key.replace(/_/g, ' ')}</p>
                                        <div className="cursor-help relative shrink-0">
                                          <Info className="w-2.5 h-2.5 text-neutral-500 hover:text-accent-cyan transition-colors" />
                                          <div className="hidden group-hover:block absolute bottom-full right-0 mb-2 w-48 p-2 bg-neutral-900 border border-neutral-700 rounded shadow-xl text-xs text-neutral-300 z-50 whitespace-normal">
                                            {tooltips[key] || tooltips.default}
                                          </div>
                                        </div>
                                      </div>
                                      <p className="text-xs font-bold text-white truncate" title={value}>{typeof value === 'number' ? value.toLocaleString(undefined, { maximumFractionDigits: 2 }) : value}</p>
                                    </div>
                                  );
                                })}
                              </div>
                            </div>
                          );
                        })()}
                      </div>
                    </motion.div>
                  )}

                  <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                    {/* Macro Context */}
                    <motion.div variants={itemVariants} className="bg-neutral-800/40 rounded-xl p-6 border border-neutral-700/50">
                      <h3 className="text-lg font-bold text-white mb-4 flex items-center gap-2">
                        <ShieldAlert className="w-5 h-5 text-accent-cyan" /> Macro Risk Profile
                      </h3>
                      <div className="space-y-4">
                        <div>
                          <p className="text-sm text-neutral-400 mb-1">Volatility Regime</p>
                          <p className="text-lg font-semibold text-white capitalize">{analysis.macro.volatility_regime}</p>
                        </div>
                        <div>
                          <p className="text-sm text-neutral-400 mb-1">Instability Score</p>
                          <div className="flex items-center gap-3">
                            <div className="flex-1 h-2 bg-neutral-700 rounded-full overflow-hidden">
                              <div 
                                className={`h-full ${analysis.macro.instability_score_1_10 > 7 ? 'bg-red-500' : analysis.macro.instability_score_1_10 > 4 ? 'bg-yellow-500' : 'bg-green-500'}`} 
                                style={{ width: `${analysis.macro.instability_score_1_10 * 10}%` }}
                              ></div>
                            </div>
                            <span className="font-bold text-white">{analysis.macro.instability_score_1_10}/10</span>
                          </div>
                        </div>
                      </div>
                    </motion.div>

                    {/* News Feed */}
                    <motion.div variants={itemVariants} className="bg-neutral-800/40 rounded-xl p-6 border border-neutral-700/50 flex flex-col h-[300px]">
                      <h3 className="text-lg font-bold text-white mb-4 flex items-center justify-between">
                        <div className="flex items-center gap-2">
                          <Newspaper className="w-5 h-5 text-accent-purple" /> Market News
                        </div>
                        <span className={`text-xs px-2 py-1 rounded font-bold uppercase ${
                          analysis.news_analysis.overall_sentiment === 'bullish' ? 'text-green-400 bg-green-500/10' :
                          analysis.news_analysis.overall_sentiment === 'bearish' ? 'text-red-400 bg-red-500/10' :
                          'text-yellow-400 bg-yellow-500/10'
                        }`}>
                          {analysis.news_analysis.overall_sentiment}
                        </span>
                      </h3>
                      <div className="flex-1 overflow-y-auto pr-2 space-y-4">
                        {analysis.news_analysis.articles.map((article, index) => (
                          <div key={index} className="group cursor-pointer">
                            <p className="font-semibold text-sm text-neutral-200 group-hover:text-accent-cyan transition-colors mb-1">{article.title}</p>
                            <p className="text-xs text-neutral-400 line-clamp-2">{article.summary}</p>
                          </div>
                        ))}
                      </div>
                    </motion.div>
                  </div>
                  
                  {/* Disclaimer */}
                  {analysis.disclaimer && (
                    <motion.div variants={itemVariants} className="text-xs text-neutral-500 mt-8 text-center italic px-4 pb-4">
                      {analysis.disclaimer}
                    </motion.div>
                  )}
                </motion.div>
              </div>
            )}
          </motion.div>
          
        </div>
      </div>
    </div>
  );
}

export default App;